### ISSUE TITLE
Sorteren Leden

### ISSUE THREAD

**Issue by wokste** [esrg-knights/Socrates#10]
Op de eetlijst zou ik graag alle leden willen kunnen sorteren op
- naam
- of ze betaald hebben

**Comment by Requinard** [comment]
betaaldstatus moet nog

**Comment by Requinard** [comment]
Deze gaat jammer genoeg niet lukken. Tabellen met checkboxen is bijna niet te doen.

**Comment by wokste** [comment]
Ik zou dit dan maar sluiten. Het lijkt in de praktijk minder nodig te zijn als ik eerst dacht.
Edit: Oh, dat had je al gedaan
