### ISSUE TITLE
Zichtbaarheid knoppen

### ISSUE THREAD

**Issue by wokste** [esrg-knights/Socrates#11]
De knop "schrijf je in voor deze eetlijst" zou niet zichtbaar moeten zijn als
- je ingeschreven bent
- de eetlijst gesloten is

De knop "schrijf je uit" zou niet zichtbaar moeten zijn als
- je niet ingeschreven bent
- de eetlijst gesloten is

**Comment by Requinard** [comment]
ce6f5ab6a0720eb9297ee0e1777b35e374c5abc1
