### ISSUE TITLE
Privacy isuues achievements

### ISSUE THREAD

**Issue by wokste** [esrg-knights/Socrates#20]
In de vorige versie van de app worden leden alleen laten zien aan leden. Nu er een achievements venster is, geldt dit niet meer.
Om te voorkomen dat niet-leden onnodig informatie over leden krijgen behoord deze informatie niet zichtbaar te zijn als een gebruiker niet is ingelogd.

**Comment by Requinard** [comment]
057e62912515bfa1c1796aefeb3d470fd8a036b0

Now fixed
