### ISSUE TITLE
fix dateformat

### ISSUE THREAD

**Issue by Aldwoni** [esrg-knights/Socrates#7]
USE_L10N is het probleem

DATETIME_FORMAT

Default: 'N j, Y, P' (e.g. Feb. 4, 2003, 4 p.m.)

The default formatting to use for displaying datetime fields in any part of the system. Note that if USE_L10N is set to True, then the locale-dictated format has higher precedence and will be applied instead. See allowed date format strings.

**Comment by Requinard** [comment]
4eafc2c
